name: Trigger Mono-Repo Build from Server

on:
  push:
    branches:
      - main

jobs:
  trigger-mono:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger mono build
        run: |
          curl -X POST \
            -H "Authorization: token ${{ secrets.GH_PAT }}" \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/Joseh254/lapsol-pos/actions/workflows/build-and-deploy.yml/dispatches \
            -d '{"ref":"main"}'
